version: "3.3"

services:
  api_node:
    container_name: api_node
    build:
      context: "./api"
      dockerfile: Dockerfile
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    ports:
      - 3333:3333